/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();

        // Original code generated by Gradle
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        // Our new code to test the fib() method.
        assertEquals(55, classUnderTest.fib(10));  // 55 = fib(10)
    }
}
